# Generated by Django 4.2.4 on 2023-08-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_data', to='contact.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'contact data',
                'verbose_name_plural': 'contacts data',
            },
        ),
    ]
