# Generated by Django 4.2.4 on 2023-08-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
